---
title: "GS"
author: "ITAM"
date: "10/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Lámina Ejemplo 3 BRugs

```{r}
library(BRugs) #Paquete que establece la conexión de OpenBUGS y R
setwd("~/Dropbox/Academia/ITAM/2020-II/Sim_S20-II/bugs/modelo1/")
Modelo <- "model{
		   prec.ybar <- n/sigma2  #Los modelos normales en BUGS usan precision, no varianza
		   prec.theta <- 1/tau2  
		   ybar ~ dnorm(theta,prec.ybar)
		  theta ~ dnorm(mu,prec.theta)}"
writeLines(Modelo, con = "Modelo.txt")
modelCheck("Modelo.txt")

datos <- "list(ybar=6, mu=2, sigma2=1, tau2=1, n=10)"
writeLines(datos, con = "datos.txt")
	
vinit <- "list(theta=0)"
writeLines(vinit, con = "vinit.txt")
	
modelData("datos.txt")

modelCompile() #compilación del modelo
#Se da un valor inicial para el modelo o se puede usar modelGenInits() para valores generados
modelInits("vinit.txt") 

modelUpdate(1000) #burn-in
samplesSet("theta") #Define el monitor de la variable
modelUpdate(10000)  #Generamos n iteraciones
#podemos usar "*" o un vector con los nombres de las variables a monitorear entre comillas
samplesStats("theta") 

a <- samplesHistory("*",mfrow=c(1,1),ask = F)
points(1001:11000,cumsum(a$theta)/(1:length(a$theta)),pch=16,cex=0.5)
samplesDensity("theta",mfrow=c(1,1))
```

# R2OpenBUGS

```{r}
library(R2OpenBUGS) 
#define el directorio de trabajo.
setwd("~/Dropbox/Academia/ITAM/2020-II/Sim_S20-II/bugs/modelo1/") 
datos <- list(ybar=6, mu=2, sigma2=1, tau2=1, n=10) #define los valores de los datos

#también se requiere especificar valores iniciales
inits <- function(){list(theta = 0)} #se requiere función para tener inicializadas múltiples cadenas
mod.sim <- R2OpenBUGS::bugs(datos, inits, model.file = "Modelo.txt",
				parameters = c("theta"), n.chains = 20,
				n.burnin = 1000, n.iter = 5000)
print(mod.sim)
plot(mod.sim)
```

```{r}
par(mar=c(3,3,1,1))
library(coda)
inits <- function(){list(theta = 0)}
#agrega la opción {\tt cdaPkg = T} para poder leer la salida a coda
mod.sim2 <- R2OpenBUGS::bugs(datos, inits, model.file = "Modelo.txt",
					 parameters = c("theta"), n.chains = 4,
				     n.burnin = 1000, n.iter = 3000, codaPkg = T)
plot(R2OpenBUGS::read.bugs(mod.sim2))
```

# JAGS

```{r}
library(rjags) 
#define el directorio de trabajo.
setwd("~/Dropbox/Academia/ITAM/2020-II/Sim_S20-II/bugs/modelo1/") 
jags <- jags.model("Modelo.txt",
            data = list(ybar=6, mu=2, sigma2=1, tau2=1, n=10), #define los valores de los datos
                        n.chains = 20,
                        n.adapt = 1000) # burn-in
update(jags,1000)

z <- jags.samples(jags,c("theta"),1000)
hist(z$theta,breaks = 50,prob=T)
```


# Ejemplos adicionales

## Ejemplo 1
```{r}
Modelo2 <- "
    model {
	Z ~ dnorm(0,1) #Hay que considerar que en BUGS se lee la precisión, no la varianza
	Y <- pow(2*Z+1,3)
	P10 <- step(Y-10) #step es la indicadora de la condición > 0 Suponemos k=10
	}
	"

writeLines(Modelo2,con="Modelo2.txt")
modelCheck("Modelo2.txt")
modelCompile()
modelGenInits() #inicializa al azar
modelUpdate(10000) #burn-in
samplesSet(c("Y","P10"))
modelUpdate(50000)

MuestraY <- samplesSample("Y")
hist(MuestraY,prob=T,breaks=100)
lines(density(MuestraY),col="red",lwd=2)

samplesStats("*")
samplesStats("P10")$mean
```

Sistematización del proceso:

```{r}
run.model <- function(modelo, muestras, datos = list(), longcadena = 10000, burnin = 0.10,
                      vinit, nchains=1,thin=1) {
	writeLines(modelo, con="modelg.txt")
	modelCheck("modelg.txt")   #Envía el modelo a BUGS, para verificar sintaxis
	if(length(datos)>0)        #Si hay datos disponibles,
	modelData(bugsData(datos)) #BRugs los pone en un archivo y los envía a BUGS
	modelCompile(nchains)        #BRugs compila el modelo
	
	if(missing(vinit)) {
		modelGenInits()           #Inicializa la cadena al azar si no hay valores iniciales
	} else {
		for(chain in 1:nchains) modelInits(bugsInits(vinit))
	}
	
	modelUpdate(longcadena*burnin) #porcentaje de las simulaciones a descartarse 
	samplesSet(muestras)
	samplesSetThin(thin)
	modelUpdate(longcadena)
}

run.model(Modelo2, muestras=c("Y","P10"),longcadena = 50000)
```


## Ejemplo 5

```{r}
modelo3 <- "model {
		for(i in 1:100) {Y[i] ~ dgamma(4,0.04)}
		sumacosto[1] <- Y[1]
		for(i in 2:100) {sumacosto[i] <- sumacosto[i-1] + Y[i]}
		for(i in 1:100) {cum.step[i] <- i * step(10000 - sumacosto[i]) } #1,2,...,M,0,...
		M <- ranked(cum.step[],100)}"

run.model(modelo3, muestras=c("M","sumacosto[100]"),longcadena = 50000)

samplesStats(c("M","sumacosto[100]"))
muestraM <- samplesSample("M")
hist(muestraM,probability = T)
lines(density(muestraM),col="red",lwd=2)
```

## Modelo de Regresión lineal

```{r}
modelo4 <- "
    model {
	for (i in 1:n) {
		logx[i] <- log(x[i])
		y[i] ~ dnorm(mu[i], tau)
		mu[i] <- beta0 + beta1*logx[i]
	}
	# priors para los parámetros de regresión
	beta0 ~ dnorm(0,100)
	beta1 ~ dnorm(0,100)
	# prior para la precisión del parámetro
	tau ~ dgamma(0.1,0.1)
	sigma <- 1/sqrt(tau)
	}
	"

run.model(modelo4, muestras=c("beta0","beta1","sigma"), 
	      datos = list(x = c(1.0, 1.5, 1.5, 1.5, 2.5, 4.0, 5.0, 5.0, 7.0,
							 8.0, 8.5, 9.0, 9.5, 9.5, 10.0, 12.0, 12.0, 13.0,
							13.0, 14.5, 15.5, 15.5, 16.5, 17.0, 22.5, 29.0,31.5),
					   y = c(1.80, 1.85, 1.87, 1.77, 2.02, 2.27, 2.15, 2.26, 2.47,
							 2.19, 2.26, 2.40, 2.39, 2.41, 2.50, 2.32, 2.32, 2.43,
							 2.47, 2.56, 2.65, 2.47, 2.64, 2.56, 2.70, 2.72, 2.57),
					   n = 27),
				   longcadena = 30000,burnin = 0.20)

```


```{r}
samplesStats("*")

beta0 <- samplesSample("beta0")
beta1 <- samplesSample("beta1")
sigma <- samplesSample("sigma")
plot(beta0,beta1,pch=16,cex=0.5)
abline(reg=lm(beta1~beta0),col="red",lwd=3)
hist(sigma, probability = T)
lines(density(sigma),col="red",lwd=2)

```

Versión de OpenBUGS

```{r}
#previamente cargado coda y R2OpenBUGS
writeLines(modelo4, con = "Modelo4.txt")

inits <- function(){list(beta0=1,beta1=1,tau=1)}	

datos = list(x = c(1.0, 1.5, 1.5, 1.5, 2.5, 4.0, 5.0, 5.0, 7.0, 8.0, 8.5, 9.0, 9.5, 9.5,
                   10.0, 12.0, 12.0, 13.0, 13.0, 14.5, 15.5, 15.5, 16.5, 17.0, 22.5,
                   29.0,31.5), 
             y = c(1.80, 1.85, 1.87, 1.77, 2.02, 2.27, 2.15, 2.26, 2.47, 2.19,
                    2.26, 2.40, 2.39, 2.41, 2.50, 2.32, 2.32, 2.43, 2.47, 2.56, 2.65, 
                    2.47, 2.64, 2.56, 2.70, 2.72, 2.57), 
             n = 27)

mod.sim1 <- R2OpenBUGS::bugs(datos,inits,model.file="Modelo4.txt", 
                 parameters=c("beta0","beta1","sigma"),
                 n.burnin = 1000, n.iter = 3000, codaPkg = T)

par(mar=c(2,2,2,1))
plot(R2OpenBUGS::read.bugs(mod.sim1))
par(mar=c(3,3,1,1))
gelman.plot(R2OpenBUGS::read.bugs(mod.sim1))
```


